Feature/nri html
shimmer52/atsukotanishita pull request #1
Opened 2020-09-30 14:15 UTC by shimmer52

HTML＆CSSコース：NRI課題
HTMLのコーディング完了

2020-09-30 14:48 UTC, piasoratech requested changes
htmlファイル内で指摘したこと以外での指摘を何点かさせてください。

- imagesフォルダ内にあるファイルの名前がicon-で始まっているものと-iconで終わっているものがそれぞれありますが、何か意図した命名でしょうか？意図したものでなければ、統一されていたほうが良いのでどちらかに統一をしましょう。
- 見出しタグがh1しか使われていません。他にも見出しとして扱える部分があるはずなので、もう一度考え直してみて下さい。

2020-09-30 14:48 UTC, piasoratech commented on index.html
> +                <a href="https://www.nri.com/jp"><img src="images/nri-logo.png" alt="NRIロゴ"></a>
この課題ではリンク先はすべて#で良いです。`href="#`としてください。

2020-09-30 14:48 UTC, piasoratech commented on index.html
> +    </nav>
HTMLの要素として`header`,`main`,`footer`のいずれかに含まれない部分はないようにしましょう。

2020-09-30 14:48 UTC, piasoratech commented on index.html
> +</html>
ファイルの最後は改行して終わらせてください。

2020-09-30 14:48 UTC, piasoratech commented on index.html
> +        <p class="copyright">Copyright(c) Nomura Research Institute, Ltd. All rights reserved.</p>
copyrightに適したタグがあるので調べて使用しましょう

2020-09-30 14:48 UTC, piasoratech commented on index.html
> +    <link rel="stylesheet" href="css/normalize.css">
まだCSSファイルを作成していないので、開発者ツールで見た時にエラーを起こしています。
一時的にコメントアウトするなどして、エラーが出ないようにしておきましょう。
![image](https://user-images.githubusercontent.com/57445698/94700869-f10b3580-0376-11eb-93f9-5de8e2431350.png)

2020-09-30 14:48 UTC, piasoratech commented on index.html
> +    <meta name="viewport" content="width=device-width, initial-scale=1.0">
今回はmetaタグでdescriptionも設定するようにして下さい。

2020-10-01 21:47 UTC, choimake approved these changes
LGTMです。次に進んでください。

2020-10-02 09:45 UTC, merged